---
nvidia_dcgm_exporter_version: 3.3.9-3.6.1

nvidia_dcgm_exporter_binary_local_dir: ""

nvidia_dcgm_exporter_git_url: https://github.com/NVIDIA/dcgm-exporter.git
nvidia_dcgm_exporter_skip_install: false

nvidia_dcgm_exporter_web_listen_address: "0.0.0.0:9400"

nvidia_dcgm_exporter_tls_server_config: {}
nvidia_dcgm_exporter_http_server_config: {}
nvidia_dcgm_exporter_basic_auth_users: {}
nvidia_dcgm_exporter_metrics_config_file: counters.csv

nvidia_dcgm_exporter_cli_args: []
nvidia_dcgm_exporter_binary_install_dir: /usr/local/bin
nvidia_dcgm_exporter_system_group: dcgmexp
nvidia_dcgm_exporter_system_user: "{{ nvidia_dcgm_exporter_system_group }}"
nvidia_dcgm_exporter_create_system_user_group: true
